//
//  MotivationQuotes.swift
//  Sunomoon
//
//  Created by Luksawee Phansri on 6/23/21.
//
import Foundation
struct MotivationQuoteData {
    let quotes = [
        MotivationQuoteModel(quote: "All my dreams can come true if I have the courage to pursue them", author: "Walt Disney"),
        MotivationQuoteModel(quote: "The secret of getting ahead is getting started", author: "Mark Twain"),
        MotivationQuoteModel(quote: "Do not limit yourself. Many people limit themselves to what they think they can do. I can go as far as my mind lets me. What I believe, remember, I can achieve", author: "Mary Kay Ash"),
        MotivationQuoteModel(quote: "The best time to plant a tree was 20 years ago. The second best time is now", author: "Chinese Proverb"),
        MotivationQuoteModel(quote: "It is hard to beat a person who never gives up", author: "Babe Ruth"),
        MotivationQuoteModel(quote: "I wake up every morning and think to myself, how far can I push this company in the next 24 hours", author: "Leah Busque"),
        MotivationQuoteModel(quote: "I need to understand that failure is not the opposite of success. It is part of success", author: "Arianna Huffington"),
        MotivationQuoteModel(quote: "I have gotta dance like nobody was watching, love like I will never be hurt, sing like nobody was listening, and live like it has heaven on earth", author: "William W. Purkey"),
        MotivationQuoteModel(quote: "Everything I can imagine is real", author: "Pablo Picasso"),
        MotivationQuoteModel(quote: "When one door of happiness closes, another opens; but often I look so long at the closed door that I do not see the one which has been opened for me", author: "Helen Keller"),
        MotivationQuoteModel(quote: "I will do one thing every day that scares me", author: "Eleanor Roosevelt"),
        MotivationQuoteModel(quote: "It is no use going back to yesterday because I was a different person then", author: "Lewis Carroll"),
        MotivationQuoteModel(quote: "Happiness is not something ready made. It comes from my actions", author: "Dalai Lama XIV"),
        MotivationQuoteModel(quote: "Whatever I am, be a good one", author: "Abraham Lincoln"),
        MotivationQuoteModel(quote: "If I have the attitude that it is going to be a great day, it usually is", author: "Catherine Pulsifier"),
        MotivationQuoteModel(quote: "I can either experience the pain of discipline or the pain of regret. The choice is mine", author: "Unknown"),
        MotivationQuoteModel(quote: "Impossible is just an opinion", author: "Paulo Coelho"),
        MotivationQuoteModel(quote: "My passion is waiting for my courage to catch up", author: "Isabelle Lafleche"),
        MotivationQuoteModel(quote: "Magic is believing in myself. If I can make that happen, I can make anything happen", author: "Johann Wolfgang Von Goethe"),
        MotivationQuoteModel(quote: "If something is important enough, even if the odds are stacked against me, I should still do it", author: "Elon Musk"),
        MotivationQuoteModel(quote: "Hold the vision, trust the process", author: "Unknown"),
        MotivationQuoteModel(quote: "Do not be afraid to give up the good to go for the great", author: "John D. Rockefeller"),
        MotivationQuoteModel(quote: "People who wonder if the glass is half empty or full miss the point. The glass is refillable", author: "Unknown"),
        MotivationQuoteModel(quote: "Just another magic day", author: "Unknown"),
        MotivationQuoteModel(quote: "One day or day one. I decide", author: "Unknown"),
        MotivationQuoteModel(quote: "It is a day. Time to motivate and make dreams and goals happen. Make it happen", author: "Heather Stillufsen"),
        MotivationQuoteModel(quote: "Goodbye blue day", author: "Kurt Vonnegut"),
        MotivationQuoteModel(quote: "I am alive, motivated and ready to slay the day", author: "Unknown"),
        MotivationQuoteModel(quote: "The hard days are what make me stronger", author: "Aly Raisman"),
        MotivationQuoteModel(quote: "If I believe it will work out, I will see opportunities. If I do not believe it will work out, I will see obstacles", author: "Wayne Dyer"),
        MotivationQuoteModel(quote: "I can waste my life drawing lines or live my life crossing them", author: "Shonda Rhimes"),
        MotivationQuoteModel(quote: "I now tried a new hypothesis. It was possible that I was more in charge of my happiness than I was allowing myself to be", author: "Michelle Obama"),
        MotivationQuoteModel(quote: "In a gentle way, I can shake the world", author: "Mahatma Gandhi"),
        MotivationQuoteModel(quote: "If opportunity does not knock, build a door", author: "Kurt Cobain"),
        MotivationQuoteModel(quote: "Do not be pushed around by the fears in my mind. Be led by the dreams in my heart", author: "Roy T. Bennett"),
        MotivationQuoteModel(quote: "Work hard in silence, let my success be the noise", author: "Frank Ocean"),
        MotivationQuoteModel(quote: "The only difference between ordinary and extraordinary is that little extra", author: "Jimmy Johnson"),
        MotivationQuoteModel(quote: "The miracle is not that I do this work but that I am happy to do it", author: "Mother Teresa"),
        MotivationQuoteModel(quote: "Never give up on a dream just because of the time it will take to accomplish it. The time will pass anyway", author: "Earl Nightingale"),
        MotivationQuoteModel(quote: "If I work on something a little bit every day, I end up with something massive", author: "Kenneth Goldsmith"),
        MotivationQuoteModel(quote: "The big secret in life is that there is no secret. Whatever my goal, I can get there if I am willing to work", author: "Oprah Winfrey"),
        MotivationQuoteModel(quote: "If I cannot do great things, do small things in a great way", author: "Napoleon Hill"),
        MotivationQuoteModel(quote: "Never allow a person to tell me no who does not have the power to say yes", author: "Eleanor Roosevelt"),
        MotivationQuoteModel(quote: "At any given moment, I have the power to say: this is not how the story is going to end", author: "Unknown"),
        MotivationQuoteModel(quote: "Amateurs sit around and wait for inspiration. The rest of us get up and go to work", author: "Stephen King"),
        MotivationQuoteModel(quote: "Nothing will work unless I do", author: "Maya Angelou"),
        MotivationQuoteModel(quote: "Do not limit my challenges. Challenge my limits", author: "Unknown"),
        MotivationQuoteModel(quote: "Whenever I find myself doubting how far I can go, remember how far I have come", author: "Unknown"),
        MotivationQuoteModel(quote: "In the middle of every difficulty lies opportunity", author: "Albert Einstein"),
        MotivationQuoteModel(quote: "Start where I am. Use what I have. Do what I can", author: "Arthur Ashe"),
        MotivationQuoteModel(quote: "Dreams do not work unless I do", author: "John C. Maxwell"),
        MotivationQuoteModel(quote: "Go the extra mile. It has never crowded there", author: "Dr. Wayne D. Dyer"),
        MotivationQuoteModel(quote: "Keep my face always toward the sunshine, and shadows will fall behind me", author: "Walt Whitman"),
        MotivationQuoteModel(quote: "What defines me is how well I rise after falling", author: "Lionel from Maid in Manhattan Movie"),
        MotivationQuoteModel(quote: "HOPE = Hold On. Pain Ends", author: "unknown"),
        MotivationQuoteModel(quote: "Make each day my masterpiece", author: "John Wooden"),
        MotivationQuoteModel(quote: "Wherever I go, go with all my heart", author: "Confucius"),
        MotivationQuoteModel(quote: "Turn my wounds into wisdom", author: "Oprah"),
        MotivationQuoteModel(quote: "I can do anything I want to if I stick to it long enough", author: "Helen Keller"),
        MotivationQuoteModel(quote: "Begin anywhere", author: "John Cage"),
        MotivationQuoteModel(quote: "Every champion was once a contender that did not give up", author: "Gabby Douglas"),
        MotivationQuoteModel(quote: "Do not dream about success. Get out there and work for it", author: "Unknown"),
        MotivationQuoteModel(quote: "I hated every minute of training, but I said, Do not quit. Suffer now and live the rest of my life as a champion", author: "Muhammad Ali"),
        MotivationQuoteModel(quote: "Opportunities do not happen. I create them", author: "Chris Grosser"),
        MotivationQuoteModel(quote: "Success is liking myself, liking what I do, and liking how I do it", author: "Maya Angelou"),
        MotivationQuoteModel(quote: "If I obey all the rules, I miss all the fun", author: "Katharine Hepburn"),
        MotivationQuoteModel(quote: "Life is not what I alone make it. Life is the input of everyone who touched my life and every experience that entered it", author: "Yuri Kochiyama"),
        MotivationQuoteModel(quote: "Never regret anything that made me smile", author: "Mark Twain"),
        MotivationQuoteModel(quote: "I must do the thing I think I cannot do", author: "Eleanor Roosevelt"),
        MotivationQuoteModel(quote: "If I want to fly, give up everything that weighs me down", author: "Buddha"),
        MotivationQuoteModel(quote: "Doubt kills more dreams than failure ever will", author: "Suzy Kassem"),
        MotivationQuoteModel(quote: "I never lose. Either I win or learn", author: "Nelson Mandela"),
        MotivationQuoteModel(quote: "Today is my opportunity to build the tomorrow I want", author: "Ken Poirot"),
        MotivationQuoteModel(quote: "Focus on being productive instead of busy", author: "Tim Ferriss"),
        MotivationQuoteModel(quote: "I do not need to see the whole staircase, just take the first step", author: "Martin Luther King Jr"),
        MotivationQuoteModel(quote: "It is not all sunshine and rainbows, but a good amount of it actually is", author: "Unknown"),
        MotivationQuoteModel(quote: "When someone says I cannot do it, do it twice and take pictures", author: "Unknown"),
        MotivationQuoteModel(quote: "I did not get there by wishing for it but by working for it", author: "Estee Lauder"),
        MotivationQuoteModel(quote: "I remembered who I was, and the game changed", author: "Lalah Deliah"),
        MotivationQuoteModel(quote: "Be happy with what I have while working for what I want", author: "Helen Keller"),
        MotivationQuoteModel(quote: "Sunshine all the time makes a desert", author: "Arabic Proverb"),
        MotivationQuoteModel(quote: "The big lesson in life is never be scared of anyone or anything", author: "Frank Sinatra"),
        MotivationQuoteModel(quote: "I am so much stronger than my excuses", author: "Unknown"),
        MotivationQuoteModel(quote: "Do not compare yourself to others. Be like the sun and the moon and shine when it is my time", author: "Unknown"),
        MotivationQuoteModel(quote: "Do not Quit", author: "Unknown"),
        MotivationQuoteModel(quote: "Do not tell everyone my plans, instead show them my results", author: "Unknown"),
        MotivationQuoteModel(quote: "I choose to make the rest of my life the best of my life", author: "Louise Hay"),
        MotivationQuoteModel(quote: "Nothing can dim the light that shines from within", author: "Maya Angelou"),
        MotivationQuoteModel(quote: "Be so good they cannot ignore me", author: "Steve Martin"),
        MotivationQuoteModel(quote: "This is a reminder to me to create my rule book and live my life the way I want it", author: "Reese Evans"),
        MotivationQuoteModel(quote: "Do the best I can. No one can do more than that", author: "John Wooden"),
        MotivationQuoteModel(quote: "Do what I can, with what I have, where I am", author: "Theodore Roosevelt"),
        MotivationQuoteModel(quote: "It is never too late to be what I might have been", author: "George Eliot"),
        MotivationQuoteModel(quote: "If I can dream it, I can do it", author: "Walt Disney"),
        MotivationQuoteModel(quote: "I can do it and get it", author: "Baz Luhrmann"),
        MotivationQuoteModel(quote: "Do not let what I cannot do interfere with what I can do", author: "Unknown"),
        MotivationQuoteModel(quote: "I can do anything that I set my mind to", author: "Benjamin Franklin"),
        MotivationQuoteModel(quote: "All I can do is the best I can do", author: "David Axelrod"),
        MotivationQuoteModel(quote: "I never know what I can do until I try", author: "William Cobbett"),
        MotivationQuoteModel(quote: "I am thankful for all of those who said no to me. It is because of them I am doing it myself", author: "Wayne W. Dyer"),
        MotivationQuoteModel(quote: "It is okay to outgrow people who do not grow. Grow tall anyways", author: "Unknown"),
        MotivationQuoteModel(quote: "The world is full of friendly people. If you cannot find one, be one", author: "Nishan Panwar"),
        MotivationQuoteModel(quote: "I cannot go back and change the beginning, but I can start where I am and change the ending", author: "C.S. Lewis"),
        MotivationQuoteModel(quote: "Yesterday I was clever, so I wanted to change the world. Today I am wise, so I am changing myself", author: "Rumi"),
        MotivationQuoteModel(quote: "I can, and I will. Watch me", author: "Carrie Green"),
        MotivationQuoteModel(quote: "A winner is a dreamer who never gives up", author: "Nelson Mandela"),
        MotivationQuoteModel(quote: "What is life without a little risk?", author: "J.K. Rowling"),
        MotivationQuoteModel(quote: "Only do what my heart tells me", author: "Princess Diana"),
        MotivationQuoteModel(quote: "If it is a good idea, go ahead and do it. It is much easier to apologize than it is to get permission", author: "Grace Hopper"),
        MotivationQuoteModel(quote: "I attribute my success to this. I never gave or took an excuse", author: "Florence Nightingale"),
        MotivationQuoteModel(quote: "A surplus of effort could overcome a deficit of confidence", author: "Sonia Sotomayer"),
        MotivationQuoteModel(quote: "Do not think or judge. Just listen", author: "Sarah Dessen, Just Listen"),
        MotivationQuoteModel(quote: "The problem is not the problem. The problem is my attitude about the problem", author: "Pirates of the Caribbean"),
        MotivationQuoteModel(quote: "Today is my opportunity to build the tomorrow I want", author: "Ken Poirot"),
        MotivationQuoteModel(quote: "Believe I can and I will", author: "Unknown"),
        MotivationQuoteModel(quote: "The best way to predict my future is to create it", author: "Abraham Lincoln"),
        MotivationQuoteModel(quote: "What is on the other side of fear? Nothing", author: "Jamie Foxx"),
        MotivationQuoteModel(quote: "Quitters never win. Winners never quit", author: "Dr. Irene C. Kassorla"),
        MotivationQuoteModel(quote: "It is never too late for a new beginning in my life", author: "Joyce Meyers"),
        MotivationQuoteModel(quote: "Action is the foundational key to all success", author: "Pablo Picasso"),
        MotivationQuoteModel(quote: "I never dreamt of success. I worked for it", author: "Estee Lauder"),
        MotivationQuoteModel(quote: "A goal is a dream with a deadline", author: "Napoleon Hill"),
        MotivationQuoteModel(quote: "Be the change that I wish to see in the world", author: "Mahatma Gandhi"),
        MotivationQuoteModel(quote: "Change is painful, but nothing is as painful as staying stuck somewhere I do not belong", author: "Mandy Hale"),
        MotivationQuoteModel(quote: "My positive action combined with positive thinking results in success", author: "Shiv Khera"),
        MotivationQuoteModel(quote: "If I talk about it, it is a dream. If I envision it, it is possible. If I schedule it, it is real", author: "Tony Robbins"),
        MotivationQuoteModel(quote: "The key to success is to start before I am ready", author: "Marie Forleo"),
        MotivationQuoteModel(quote: "I want to be remembered as the one who tried", author: "Dr. Dorothy Height"),
        MotivationQuoteModel(quote: "The trouble is, I think I have time", author: "Buddha"),
        MotivationQuoteModel(quote: "I cannot let my failures define me. I have to let my failures teach me", author: "Barack Obama"),
        MotivationQuoteModel(quote: "Stop being afraid of what could go wrong, and start being excited about what could go right", author: "Tony Robbins"),
        MotivationQuoteModel(quote: "Success is going from failure to failure without losing my enthusiasm", author: "Winston Churchill"),
        MotivationQuoteModel(quote: "No matter what people tell me, words and ideas can change the world", author: "Robin Williams"),
        MotivationQuoteModel(quote: "A negative mind will never give me a positive life", author: "Unknown"),
        MotivationQuoteModel(quote: "Take the risk or lose the chance", author: "Unknown"),
        MotivationQuoteModel(quote: "Life is like a movie. Write my ending. Keep believing", author: "Jim Hensen"),
        MotivationQuoteModel(quote: "If it does not challenge me, it does not change me", author: "Fred DeVito"),
        MotivationQuoteModel(quote: "A dream does not become reality through magic. It takes sweat, determination and hard work", author: "Colin Powell"),
        MotivationQuoteModel(quote: "Still, I rise", author: "Maya Angelou"),
        MotivationQuoteModel(quote: "What is coming is better than what is gone", author: "Unknown"),
        MotivationQuoteModel(quote: "Do something today that my future self will thank you for", author: "Unknown"),
        MotivationQuoteModel(quote: "My only limit is my mind", author: "Unknown"),
        MotivationQuoteModel(quote: "The difference between who I am and who I want to be is what I do", author: "Unknown"),
        MotivationQuoteModel(quote: "I am not a product of my circumstances. I am a product of my decisions", author: "Stephen Covey"),
        MotivationQuoteModel(quote: "Sometimes it is okay to not be okay", author: "Megan Devine")
    ]
    
    func getQuote(quoteNumber: Int) -> String {
        return quotes[quoteNumber].quote
    }
    
    func getAuthor(quoteNumber: Int) -> String {
        return quotes[quoteNumber].author
    }
    
    func getNumberOfQuotes() -> Int {
        return quotes.count
    }
}
