//
//  HoroscopeData.swift
//  Sunomoon
//
//  Created by Luksawee Phansri on 7/9/21.
//

import Foundation
struct TarotData {
    let tarot = [
        // set 1
        TarotModel(set: 1, tarotCardNumber: 0, tarotCard: "The Fool", tarotMeaning: "Expect the unexpected. Don't even expect that much. Today could be a wild ride, and you may instigate some of it in the spirit of fun, suggests the Fool card. Play it safe and stay out of trouble if you can, but it could be hard at times. Don't fret over any little mistakes today. By tonight or at least tomorrow, it may be hard to tell who made them if anyone even recalls them.", tarotCardPic: "TheFool"),
        TarotModel(set: 1, tarotCardNumber: 1, tarotCard: "The Magician", tarotMeaning: "You have a magic touch today. The right word or action at the right time can instantly turn things around and morph a challenge into an easy opportunity. This is not something to take for granted or to exploit, though. Use your power with a very light touch, if at all. It's possible that a mere thought or unspoken intention could have influence.", tarotCardPic: "TheMagician"),
        TarotModel(set: 1, tarotCardNumber: 2, tarotCard: "The High Priestess", tarotMeaning: "Let intuition be your guide today, and you won't go too far wrong. If something doesn't need to be done or delivered instantly, take your time and let events, situations, and people claim the time and attention they seem to want. Things want to sort themselves out for you in the best ways. Don't introduce complications. Be decisive when necessary but otherwise step up, too, and be pleasantly surprised.", tarotCardPic: "TheHighPriestess"),
        TarotModel(set: 1, tarotCardNumber: 3, tarotCard: "The Empress", tarotMeaning: "Be ambitious today, in a subtle way, and meet with a lot of cooperation and goodwill. Your ambition does not have to be grandiose. Concentrate on small projects and sweep away a lot of loose ends, and complete things that have been long lingering. Act and speak with authority, and be fully respected. Do as much as you can today, and don't look back.", tarotCardPic: "TheEmpress"),
        TarotModel(set: 1, tarotCardNumber: 4, tarotCard: "The Emperor", tarotMeaning: "You'll need determination and perseverance to accomplish anything of substance today. Pick something to do and stick with it until the end of the day. If you put effort, you should be able to make a huge headway. Even if not, your single-minded approach will attract allies for tomorrow. You have more influence and authority than you suspect. Use them wisely.", tarotCardPic: "TheEmperor"),
        TarotModel(set: 1, tarotCardNumber: 5, tarotCard: "The Hierophant", tarotMeaning: "Save those creative or fancy-free activities for another day and focus on the nuts and bolts. If you've been putting off doing something necessary but not fun, knock it out now and then feel accomplished when finished. You can earn a lot of regard and admiration for this. You won't be allowed to keep too low a profile, so step up and do what's important for today. It would be best if you encountered no resistance.", tarotCardPic: "TheHierophant"),
        TarotModel(set: 1, tarotCardNumber: 6, tarotCard: "The Lovers", tarotMeaning: "The world may seem to be working overtime to baffle or confuse you, but you don't have to take the bait. If you're offered something that seems too perfectly tailored to your tastes or desires, it's OK to be graciously skeptical. You can appear cautious rather than distrustful. Keep things simple today and minimize getting upset by torn or unsettled feelings.", tarotCardPic: "TheLovers"),
        TarotModel(set: 1, tarotCardNumber: 7, tarotCard: "The Chariot", tarotMeaning: "If you've been working hard toward some goal or specific result, you could see victory today. Feel like a winner, project the confidence of a winner, and perhaps behave as though you have already won. Keep your spirits high no matter what happens, and be pleased with how many people are happy for you. No matter how huge or trivial, it is still a big step forward.", tarotCardPic: "TheChariot"),
        TarotModel(set: 1, tarotCardNumber: 8, tarotCard: "Strength", tarotMeaning: "Act with boldness, but not too much, and make this an easy and productive day. If something challenging or unexpected arises at work or with family, be receptive and stand your ground. Don't push back until you know what it is you're up against. Then if needed, give as well as you get. You can do this tactfully.", tarotCardPic: "Strength"),
        TarotModel(set: 1, tarotCardNumber: 9, tarotCard: "The Hermit", tarotMeaning: "It might be a busy day, but try to take some time for yourself. Any time you spend meditating or settling your mind will be time well spent. It doesn't have to be spent sitting around and being idle all day. Staring pensively into that cup of tea for a few moments can be equally beneficial. Calm your mind and your heart and make it an at-peace day.", tarotCardPic: "TheHermit"),
        TarotModel(set: 1, tarotCardNumber: 10, tarotCard: "Wheel of Fortune", tarotMeaning: "Restlessness and boredom could slow you down and take you off on some unintended tangent. If you can't break free of the usual routine today, do what's necessary and perhaps schedule more delicate tasks for another time when it will be easier to be precise and attend to details. Know your limits, and if possible, don't take on something that will only frustrate you. If you must, start slow.", tarotCardPic: "WheelofFortune"),
        TarotModel(set: 1, tarotCardNumber: 11, tarotCard: "Justice", tarotMeaning: "You may be dealing with people who feel inferior or weaker than you, so take care and not run over anyone. Equally, they do not have to serve as an excuse for you to go slower or do less than you know necessary. Be firm but not too firm, determined but not too determined. Get a lot of good work done.", tarotCardPic: "Justice"),
        TarotModel(set: 1, tarotCardNumber: 12, tarotCard: "The Hanged Man", tarotMeaning: "Be calm, proactive, and don't exhaust yourself with endless fear. Any number of things might backfire or go wrong today, just like any other day, and there is little if anything extraordinary to be fearful about now. Your basic sense of insecurity may be higher than usual today, but this will pass soon. Take heart and be your usual brave self.", tarotCardPic: "TheHangedMan"),
        TarotModel(set: 1, tarotCardNumber: 13, tarotCard: "Death", tarotMeaning: "A change has been in the air for some time, and today the actual transformation could happen. There's nothing to be afraid of, or to dread, or to fear losing. Room is being made, and energy is being set aside for something new and better for you. It could be something small or something large, but whatever it is will be meaningful and affect your daily life.", tarotCardPic: "Death"),
        TarotModel(set: 1, tarotCardNumber: 14, tarotCard: "Temperance", tarotMeaning: "Pace yourself today and get more done than you might imagine as the day begins. It's all right to be tired from time to time. It doesn't have to cripple all your plans for the day. Maintain a sensible balance, remember to eat healthy, take a short break once and a while, and don't aim too high. There's plenty of work to be done that you can handle with ease.", tarotCardPic: "Temperance"),
        TarotModel(set: 1, tarotCardNumber: 15, tarotCard: "The Devil", tarotMeaning: "There may be very little that you can change or have much effect on today. It may not exactly feel like the day has been fated to be a certain way, but you may have that suspicion at times. You can fit in with whatever happens and get some satisfaction and success anyway. Someone who usually argues against you may turn around and agree with you about something important.", tarotCardPic: "TheDevil"),
        TarotModel(set: 1, tarotCardNumber: 16, tarotCard: "The Tower", tarotMeaning: "The biggest danger you face today is being aloof and thus fail to see an approaching problem. This can cost you the chance to intercept the difficulty and minimize it, if not avoid it together. Pay attention without getting paranoid, and take nothing and no one for granted. Danger may not lurk within every single shadow, but a small misstep can sometimes cause problems that are way out of proportion to the cause.", tarotCardPic: "TheTower"),
        TarotModel(set: 1, tarotCardNumber: 17, tarotCard: "The Star", tarotMeaning: "You can make today memorable purely by the strength of your unfailing hope for all things to work out for the best. No matter how chaotic the events of the day, how confused or how many mixed messages people give you, especially at work, your innate hopeful spirit will cut through most of the mist and give you good results. Look forward to many satisfying encounters, however little or much gets done.", tarotCardPic: "TheStar"),
        TarotModel(set: 1, tarotCardNumber: 18, tarotCard: "The Moon", tarotMeaning: "You may be putting yourself under more stress and pressure than anyone or anything else going on around you. It's not necessary to beat yourself up emotionally like this. Things are fine, and you can make things even better if you curtail the urge to obsessively dwell on only what and who is letting you down. Be your own best friend and give yourself credit for what you're doing right.", tarotCardPic: "TheMoon"),
        TarotModel(set: 1, tarotCardNumber: 19, tarotCard: "The Sun", tarotMeaning: "Little or nothing will slow you down or be daunting to you today. You have so much inner and physical strength, that people will have trouble keeping up with you. Do something special today, or perhaps excel at something significant and challenging that will be easily within your grasp. You may find out later that you were dazzling and that you inspired several people to more energetically pursue their passions.", tarotCardPic: "TheSun"),
        TarotModel(set: 1, tarotCardNumber: 20, tarotCard: "The Judgement", tarotMeaning: "You can get a great deal done today and strengthen some relationships by being tactfully straightforward and not adding complications to anyone's day. With no hidden agenda or any manipulative tricks, you can win people's cooperation and have them agree with you most of the time. Keep things simple and stick to the basics to see the best and happiest results.", tarotCardPic: "TheJudgement"),
        TarotModel(set: 1, tarotCardNumber: 21, tarotCard: "The World", tarotMeaning: "People may come to you for help in making a difficult decision or two. This will be second nature to you, and no decision will be beyond your capabilities. The World is not so big that it can hold choices you cannot make or decisions that could overwhelm you. Be exceptionally confident, capable, and at ease in public and private sectors today.", tarotCardPic: "TheWorld"),
        
        // set 2
        TarotModel(set: 2, tarotCardNumber: 0, tarotCard: "The Fool", tarotMeaning: "The day may be full of confusion, but you don't have to go through it naively and unaware of what's happening around you. It's not a good day to flirt with taking silly risks, some of which might turn out to be semi-dangerous or costly. You may be too hyper to want to play it safe, but at least make an effort not to be naive or irresponsible.", tarotCardPic: "TheFool"),
        TarotModel(set: 2, tarotCardNumber: 1, tarotCard: "The Magician", tarotMeaning: "Be organized, stick to your routine, and don't gloss over any steps if you want to get the results you have in mind. This could be a day better for practice than for performance. Do your best, be forgiving of yourself about any minor slip-ups, and have no regrets. You know what you're already good at, so focus on that and glide through the day.", tarotCardPic: "TheMagician"),
        TarotModel(set: 2, tarotCardNumber: 2, tarotCard: "The High Priestess", tarotMeaning: "There may be a moment or two when you feel responsible for everything in the world and like you must take care of everyone. Relax, let this wash over you, and let it go. It's not a burden. A demonstration of how connected you are to people things in your own life and how much you care. That's a good thing.", tarotCardPic: "TheHighPriestess"),
        TarotModel(set: 2, tarotCardNumber: 3, tarotCard: "The Empress", tarotMeaning: "Some big new opportunity could come your way today. Focus your attention on the one thing you want most to have happened, and it won't be able to resist you. You can be persuasive and graceful, smooth and strong all at the same time. Act with quiet confidence and be admired later. Today, enjoy having people listen and do almost everything you suggest.", tarotCardPic: "TheEmpress"),
        TarotModel(set: 2, tarotCardNumber: 4, tarotCard: "The Emperor", tarotMeaning: "Kindness will take you very far today. It's not a show of weakness or inferiority to engage in that random act of kindness. Think of it as acting out of the generosity of spirit. The bigger your heart today, the more respect and cooperation will come your way. Make sure your kindness is genuine and from a genuine place. Then you're virtually unassailable.", tarotCardPic: "TheEmperor"),
        TarotModel(set: 2, tarotCardNumber: 5, tarotCard: "The Hierophant", tarotMeaning: "It's essential to stick with the plan already in place and be loyal to those who are already committed to you. You're not a part of a team as you are the leader of a group. You should treat others properly and look after their needs, especially the tiny personal ones.", tarotCardPic: "TheHierophant"),
        TarotModel(set: 2, tarotCardNumber: 6, tarotCard: "The Lovers", tarotMeaning: "Indecision is not necessarily a bad thing but taken too extreme can make you pessimistic and defeatist. Take the time you need to make the choices you need but don't get bogged down and grind to a halt. Take yourself in hand and refuse to feel helpless in the face of a challenging situation. Refuse to be rushed by anyone, too.", tarotCardPic: "TheLovers"),
        TarotModel(set: 2, tarotCardNumber: 7, tarotCard: "The Chariot", tarotMeaning: "It may start as an ordinary day, but a situation may arise that uncovers talents that you had no clue you had. Be adaptable and be willing to say, Yes, I'll give that a try, rather than automatically saying, Well, I'm not sure. I've never done that before. Be positive, optimistic, and sure of yourself. It's the perfect day to learn something useful and profitable as well as exciting.", tarotCardPic: "TheChariot"),
        TarotModel(set: 2, tarotCardNumber: 8, tarotCard: "Strength", tarotMeaning: "It may be fun to take a risk or two, but this is not the day for it. You can fight your way through any difficulty, but why make work for yourself or put yourself in harm's way? Remember, harm comes in more forms than just what is physical. If you need to blow off steam and exert your power, maybe take it to the gym.", tarotCardPic: "Strength"),
        TarotModel(set: 2, tarotCardNumber: 9, tarotCard: "The Hermit", tarotMeaning: "Think twice before you speak or act and avoid any slip-up or oversight that could make extra work for you tomorrow. Exercise more discretion, check the facts and don't automatically believe everything that you're told. Be clear that you're not suspecting the world of lying to you; you're simply prudent and cautious. It shows how much you care about getting things set right for everyone.", tarotCardPic: "TheHermit"),
        TarotModel(set: 2, tarotCardNumber: 10, tarotCard: "Wheel of Fortune", tarotMeaning: "Whatever you have planned or prepared for today, it probably won't happen according to the script. Be flexible and expect the unexpected. It may not be anything big, so don't completely abandon your plan unless you must. It could just be a day of endless interruptions. Keep that sense of humor handy, and maybe find an inspiring idea or two in it all.", tarotCardPic: "WheelofFortune"),
        TarotModel(set: 2, tarotCardNumber: 11, tarotCard: "Justice", tarotMeaning: "Take everything and everyone a little bit more seriously today without getting grim about it. People may bring you requests or problems that they think are shaking up their world, and you should offer at least a token of respect for their worries and needs. None of this puts any pressure on you unless you get emotionally involved. Remember, you have neither the power nor responsibility to fix it all.", tarotCardPic: "Justice"),
        TarotModel(set: 2, tarotCardNumber: 12, tarotCard: "The Hanged Man", tarotMeaning: "Trust may have been violated, or a broken promise may hurt a relationship, or you sense that this might happen soon. Until you know for sure who and what might be involved, take no action, although the discreet question asked of a trustworthy person might be all right, though still risky. Make no accusations but respect your self-interest.", tarotCardPic: "TheHangedMan"),
        TarotModel(set: 2, tarotCardNumber: 13, tarotCard: "Death", tarotMeaning: "Though no great demands may be made of you today, you may feel lackluster and just not setting the world on fire as you like to do. Everybody has a low energy day from time to time. Perhaps you've been pushing it too hard for too many days in a row and need a short break. Don't be lazy but be extra good to yourself. Tomorrow will be brighter.", tarotCardPic: "Death"),
        TarotModel(set: 2, tarotCardNumber: 14, tarotCard: "Temperance", tarotMeaning: "A little emotional distance is called for to keep things peaceful and to work smoothly. You may be very sentimental or attached to certain issues or other people's opinions of you, but don't let this rule how the day goes. Don't let anyone casually or ignorantly hurt your feelings. They may not even know what they're doing. Stay functional and keep your emotional guards up.", tarotCardPic: "Temperance"),
        TarotModel(set: 2, tarotCardNumber: 15, tarotCard: "The Devil", tarotMeaning: "Your instincts may be heightened and a bit off today, and this could lead you to make some wrong decisions or assumptions. Then, you run the risk of pouncing on these assumptions and acting out of a bad impulse. Keep your emotions under control and back away from impulsive actions of any kind. Today they are traps that lead to embarrassment at best and harmful at worst.", tarotCardPic: "TheDevil"),
        TarotModel(set: 2, tarotCardNumber: 16, tarotCard: "The Tower", tarotMeaning: "Your emotions and instincts are working overtime today, and this can distract you from doing the simplest of things. You may encounter some difficulties today. They should be small ones - you will create more problems for yourself by being too psychically overactive. If someone is preoccupied with you and wishing you to have a rough day, you'll know it but maybe not know who it is.", tarotCardPic: "TheTower"),
        TarotModel(set: 2, tarotCardNumber: 17, tarotCard: "The Star", tarotMeaning: "You enjoy an extra dose of protection today, so approach the day with confidence and a great sense of graciousness. Your angels are voluntarily working overtime on your behalf, so take advantage of all opportunities to do good and to make progress in your daily life. Do a nice deed for someone else and know you've been rewarded in advance. More blessings will be on the way.", tarotCardPic: "TheStar"),
        TarotModel(set: 2, tarotCardNumber: 18, tarotCard: "The Moon", tarotMeaning: "You may be dwelling on your weakness or discomfort, and those things may be real enough, but take heart and know that these things are also temporary and are not going to last much longer. You underestimate or overlook your great powers of recovery and self-healing. You have too much love of life to be kept down for long. Give yourself a break and relax a bit.", tarotCardPic: "TheMoon"),
        TarotModel(set: 2, tarotCardNumber: 19, tarotCard: "The Sun", tarotMeaning: "Not only may you be inherently happy today, but you'll also be able to explore all manner of intellectual problems, puzzles, and concerns. Great satisfaction can come from even the smallest insight. If you can connect with the right person, you may have a conversation that will enrich and inform you for months to come. You may be attracted to more difficult problems today, and you'll be up to the challenge.", tarotCardPic: "TheSun"),
        TarotModel(set: 2, tarotCardNumber: 20, tarotCard: "The Judgement", tarotMeaning: "Change has been coming your way for a while now, and today you may see the first explicit features. What happens today is only a beginning, and you may look back in a few days/weeks/months and recognize that your life is in the process of making a turn for the better. It's the nature of life not to stay the same, and you are moving forward now.", tarotCardPic: "TheJudgement"),
        TarotModel(set: 2, tarotCardNumber: 21, tarotCard: "The World", tarotMeaning: "You may not expect or even want it. Still, today you will be properly acknowledged and even honored for a skill, talent, or accomplishment. Your big heart will be appreciated. If only in the form of praise, some sort of public reward is possible, which can be transformed into something more tangible later. If not seeking validation or kudos, be on the alert because it's coming. You've earned it!", tarotCardPic: "TheWorld")
    ]
    
    func getTarotCard(set: Int, tarotCardNumber: Int) -> String {
        if(set == 1){
            return tarot[tarotCardNumber].tarotCard
        } else {
            return tarot[22 + tarotCardNumber].tarotCard
        }
    }
    
    func getTarotMeaning(set: Int, tarotCardNumber: Int) -> String {
        if(set == 1){
            return tarot[tarotCardNumber].tarotMeaning
        } else {
            return tarot[22 + tarotCardNumber].tarotMeaning
        }
    }
    
    func getTarotCardPic(set: Int, tarotCardNumber: Int) -> String {
        if(set == 1){
            return tarot[tarotCardNumber].tarotCardPic
        } else {
            return tarot[22 + tarotCardNumber].tarotCardPic
        }
    }
    
    func getNumberOfTarot() -> Int {
        return tarot.count
    }
}
